export const GET_SUMMARY = "GET_SUMMARY";
export const GET_SUMMARY_FAIL = "GET_SUMMARY_FAIL";
export const SET_LOADING = "SET_LOADING";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_COUNTRIES_PER_PAGE = "SET_COUNTRIES_PER_PAGE";