export const GET_ALL_DATA = "GET_ALL_DATA";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRY_DAY_ONE_STATUS_LIVE =
  "GET_COUNTRY_DAY_ONE_STATUS_LIVE";
export const GET_COUNTRY_DAY_ONE_STATUS = "GET_COUNTRY_DAY_ONE_STATUS";
export const GET_COUNTRY_DAY_ONE_TOTAL_STATUS =
  "GET_COUNTRY_DAY_ONE_TOTAL_STATUS";
export const GET_COUNTRY_STATUS = "GET_COUNTRY_STATUS";
export const GET_COUNTRY_STATUS_TOTAL = "GET_COUNTRY_STATUS_TOTAL";
export const LIVE_COUNTRY_STATUS_AFTER_DATE = "LIVE_COUNTRY_STATUS_AFTER_DATE";
export const LIVE_COUNTRY_STATUS = "LIVE_COUNTRY_STATUS";
export const GET_SUMMARY = "GET_SUMMARY";
export const GET_ERROR = "GET_ERROR";
export const SET_ERROR = "SET_ERROR";
