export const GET_ALL_DATA = "GET_ALL_DATA";
export const GET_ALL_DATA_SUCCESS = "GET_ALL_DATA_SUCCESS";
export const GET_ALL_DATA_FAIL = "GET_ALL_DATA_FAIL";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS";
export const GET_COUNTRIES_FAIL = "GET_COUNTRIES_FAIL";
export const GET_COUNTRY_DAY_ONE_STATUS_LIVE =
  "GET_COUNTRY_DAY_ONE_STATUS_LIVE";
export const GET_COUNTRY_DAY_ONE_STATUS_LIVE_SUCCESS =
  "GET_COUNTRY_DAY_ONE_STATUS_LIVE_SUCCESS";
export const GET_COUNTRY_DAY_ONE_STATUS_LIVE_FAIL =
  "GET_COUNTRY_DAY_ONE_STATUS_LIVE_FAIL";
export const GET_COUNTRY_DAY_ONE_STATUS = "GET_COUNTRY_DAY_ONE_STATUS";
export const GET_COUNTRY_DAY_ONE_STATUS_SUCCESS =
  "GET_COUNTRY_DAY_ONE_STATUS_SUCCESS";
export const GET_COUNTRY_DAY_ONE_STATUS_FAIL =
  "GET_COUNTRY_DAY_ONE_STATUS_FAIL";
export const GET_COUNTRY_DAY_ONE_TOTAL_STATUS =
  "GET_COUNTRY_DAY_ONE_TOTAL_STATUS";
export const GET_COUNTRY_DAY_ONE_TOTAL_STATUS_SUCCESS =
  "GET_COUNTRY_DAY_ONE_TOTAL_STATUS_SUCCESS";
export const GET_COUNTRY_DAY_ONE_TOTAL_STATUS_FAIL =
  "GET_COUNTRY_DAY_ONE_TOTAL_STATUS_FAIL";
export const GET_COUNTRY_STATUS = "GET_COUNTRY_STATUS";
export const GET_COUNTRY_STATUS_SUCCESS = "GET_COUNTRY_STATUS_SUCCESS";
export const GET_COUNTRY_STATUS_FAIL = "GET_COUNTRY_STATUS_FAIL";
export const GET_COUNTRY_STATUS_TOTAL = "GET_COUNTRY_STATUS_TOTAL";
export const GET_COUNTRY_STATUS_TOTAL_SUCCESS =
  "GET_COUNTRY_STATUS_TOTAL_SUCCESS";
export const GET_COUNTRY_STATUS_TOTAL_FAIL = "GET_COUNTRY_STATUS_TOTAL_FAIL";
export const LIVE_COUNTRY_STATUS_AFTER_DATE = "LIVE_COUNTRY_STATUS_AFTER_DATE";
export const LIVE_COUNTRY_STATUS_AFTER_DATE_SUCCESS =
  "LIVE_COUNTRY_STATUS_AFTER_DATE_SUCCESS";
export const LIVE_COUNTRY_STATUS_AFTER_DATE_FAIL =
  "LIVE_COUNTRY_STATUS_AFTER_DATE_FAIL";
export const LIVE_COUNTRY_STATUS = "LIVE_COUNTRY_STATUS";
export const LIVE_COUNTRY_STATUS_SUCCESS = "LIVE_COUNTRY_STATUS_SUCCESS";
export const LIVE_COUNTRY_STATUS_FAIL = "LIVE_COUNTRY_STATUS_FAIL";
export const GET_SUMMARY = "GET_SUMMARY";
export const GET_SUMMARY_SUCCESS = "GET_SUMMARY_SUCCESS";
export const GET_SUMMARY_FAIL = "GET_SUMMARY_FAIL";
export const GET_ERROR = "GET_ERROR";
export const SET_ERROR = "SET_ERROR";
export const IS_LOADING = "IS_LOADING";
